### ISSUE TITLE
QOF version 0.8.4

### ISSUE THREAD

**Issue by linas** [codehelp/qof#1]
Hi Neil,

It's been a very long time ... hey I am trying to build the "gnome time tracker"  https://github.com/linas/gnotime  which has QOF as a dependency. Scouring the interwebs, it appears that the latest version of QOF is version 0.8.4 but the latest that I have (and the latest in this repo) is 0.7.5 Now, that latest version is supposedly on http://qof.alioth.debian.org/ but Alioth was decommissioned in 2019, and moved to "Salsa" which does not have QOF on it.  Care to make any comments about this?

p.s. I might make a pull request containing minor updates. Like renaming `README` to `README.md` and anything else that pops up.

p.p.s I'm at linasvepstas@gmail.com for a more private channel, if anything private is to be said.

**Comment by linas** [comment]
Never mind. I see that `configure.,ac` says version 0.8.8 so I'm not sure where I saw 0.7.5. 

Closing this. But "hi" anyway!  Hope all is going well.

**Comment by ryandesign** [comment]
> I'm not sure where I saw 0.7.5

0.7.5 is the latest version posted [at SourceForge](https://sourceforge.net/projects/qof/). The SourceForge project is the one that comes up in search results.
